### ISSUE TITLE
Adding custom endpoints/handlers to resources

### ISSUE THREAD

**Issue by alexanderritola** [univedo/api2go#106]
It's likely that I'm misunderstanding how this package should be used, so it's probably easiest to explain what I'm trying to accomplish since I imagine there is a good reason `API.router` is private.

If I have a userResource that stores a username and passwordHash, like in the crud_example, and I can create new users by sending a POST request to `/v0/users/`, how could I add a custom endpoint with a custom handler, such as `/v0/users/login` and `/v0/users/logout`?

**Comment by wwwdata** [comment]
Hi, yes api.router is private but we have a function to return it.

```go
// Handler returns the http.Handler instance for the API.
func (api *API) Handler() http.Handler {
	return api.router
}
```

You can then create a mux and combine your own Handlers with our http.Handler

For example something like this

```go
mux := http.NewServeMux()
mux.Handle("/v1/login", yourLoginHandler)
mux.Handle("/", api.Handler())
```

It would also be possible to register your own julienschmidt httprouter and combine them both. That would also make sense if you have a lot of custom routes and need performance or want to extract parameters out of the url and so on ...

**Comment by wwwdata** [comment]
Thank you for this excellent question. It gave me a better idea. This is the ultimate solution! You can cast the http.Handler back to an httprouter... why didn't I think about this at first :P 

```go
handler := api.Handler().(*httprouter.Router)
// It is also possible to get the instance of julienschmidt/httprouter and add more custom routes!
handler.GET("/hello-world", func(w http.ResponseWriter, r *http.Request, _ httprouter.Params) {
	fmt.Fprint(w, "Hello World!\n")
})
http.ListenAndServe(":31415", handler)
```

I added this to our [example](https://github.com/univedo/api2go/blob/master/examples/crud_example.go#L391).

**Comment by alexanderritola** [comment]
Thanks for the fast response!

Wow, the casting solution seems very elegant, glad my question was helpful! In case anyone see this and like me, has no idea what casting is, I found this [article on type assertions](http://blog.denevell.org/golang-interface-type-assertions-switch.html) helpful.

I'm loving api2go, thanks a bunch!

**Comment by sharpner** [comment]
Heya! @wwwdata thanks for the fast reply :) 
I would recommend the mux solution, since the upcast relies on an internal API that might be subject to change. And relying on a private internal datatype is often dangerous and can break your application. 

Glad you enjoy api2go :)

**Comment by wwwdata** [comment]
Hm. We could make a second function called Router() that directly returns the httprouter instance. Then no type cast is needed and nothing is dangerous. That seems not so hacky. I think we should do that.

**Comment by sharpner** [comment]
Yeah, that certainly is the better solution. +1
