### ISSUE TITLE
I want your marshalling and types, not your server

### ISSUE THREAD

**Issue by parkr** [univedo/api2go#59]
Hi!

Nifty project! I was hoping to use pieces of it to make our JSON-generation easier, but alas there's a lot of overhead with the server stuff that we're not interested in. Thoughts on breaking out serialization and the JSON API types into their own subpackages? :smile: 

Thanks for writing this!

**Comment by wwwdata** [comment]
Splitting it up shouldn't be any problem at all. What does everybody else think?

**Comment by lucas-clemente** [comment]
Makes sense. Right now you can already use the marshal and unmarshal functions without the REST stuff (and I guess the compiler should strip the rest out), but splitting it upon a nicer solution :)

**Comment by parkr** [comment]
Thanks guys :)
