### ISSUE TITLE
Lots of "links"

### ISSUE THREAD

**Issue by parkr** [univedo/api2go#60]
I plugged a struct into `api2go.MarshalToJSON` and it gave me a multi-layered object, the middle layer being a `links` object. Super weird:

```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/univedo/api2go"
)

type Identity struct {
	UserId int64    `json:"user_id"`
	Scopes []string `json:"scopes"`
}

type Identities struct {
	Identities []Identity `json:"identities"`
}

func main() {
	var response []byte

	identity := Identity{1234, []string{"user_global"}}

	response, _ = api2go.MarshalToJSON(identity)
	fmt.Println(string(response))

	response, _ = json.Marshal(Identities{[]Identity{identity}})
	fmt.Println(string(response))
}
```

The outputs:

```json
{"identities":{"links":{"scopes":["user_global"]},"userId":1234}}
{"identities":[{"user_id":1234,"scopes":["user_global"]}]}
```

The first is not what I'm looking for, the second *is* what I'm looking for. Am I misunderstanding your API?

**Comment by wwwdata** [comment]
no, you are right, the first output here is not correct and should look like the second, that you did manually. It's weird that the `Identity` struct is put into a `links` object in the json. I will write a test later to verify this and try to fix it!

**Comment by parkr** [comment]
Thank you!!!

**Comment by wwwdata** [comment]
Ah, now I see the problem.

```go
type Identity struct {
    UserId int64    `json:"user_id"`
    Scopes []string `json:"scopes"`
}
```

here, the field `ID` is missing. In our library it is necessary to always have a field ID. So therefore the strange behavior occurs. If you change it to:

```go
type Identity struct {
	ID          int64    
	Scopes []string `json:"scopes"`
}
```

the output is 

```json
{
    "identities": {
        "id": "1234",
        "links": {
            "scopes": [
                "user_global"
            ]
        }
    }
}
```

which is a little bid better. But there still is the issue that `scopes` gets in the `links` object in the json which in your case is not correct because `Scopes` is not a linked struct, it's a field of `Identity` and we want to achieve this json output as previously posted by you:

```json
{
    "identities": [
        {
            "id": 1234,
            "scopes": [
                "user_global"
            ]
        }
    ]
}
```

so, that's what should be fixed, right?

**Comment by parkr** [comment]
I'd love to be able to use it without the `ID` at all – in this case, we're fetching a resource and want to omit the ID if empty (in our case, it's not a property we ever set). That would be ideal, but tell me what's possible and we can work from there.

**Comment by wwwdata** [comment]
Ok, I was able to fix the first issue I pointed out, now I will look into the second one which is marshalling it without the `ID` field.

**Comment by parkr** [comment]
@wwwdata YOU ROCK!

**Comment by wwwdata** [comment]
hm, marshalling a struct without an ID field seems to work fine too. I will commit a test soon. The only problem is that you are not allowed to use something like `UserID` where the `ID` is capitalized beacuse that is an indicator for a referenced struct. So api2go thinks you want to link another `User` struct here with a 1:1 relationship. But as long as you are using `UserId` it works fine, except for the json annotations which are ignored. 

But in my opinion we should include a switch from camelCase to snake_case that is come sort of configuration option. Afaik these 2 variants are officially recommended by jsonapi.org

**Comment by parkr** [comment]
> The only problem is that you are not allowed to use something like UserID where the ID is capitalized beacuse that is an indicator for a referenced struct. So api2go thinks you want to link another User struct here with a 1:1 relationship. But as long as you are using UserId it works fine, except for the json annotations which are ignored.

Hm!! I'll try that tomorrow.

> But in my opinion we should include a switch from camelCase to snake_case that is come sort of configuration option. Afaik these 2 variants are officially recommended by jsonapi.org

Not sure. I'm sure @rodaine could tell you. My personal preference is for snake_case in the JSON, and camelCase in Go.

**Comment by wwwdata** [comment]
ok, ill open a feature issue for camel/snake_case JSON output and a PR for the bugfix here :)

**Comment by rodaine** [comment]
Late to the discussion here but the case is up to the implementer, imo. For example, snake case is typical for mongo keys and the convention may bleed into the project. As long as it's consistent, I can see value in either. :+1:
