### ISSUE TITLE
Compound Documents show under 'linked' not 'included' as per specification

### ISSUE THREAD

**Issue by ben-crowhurst** [univedo/api2go#71]
Given JSONAPI 1.0 will not be ratified until the end of the month. I'm not sure of the importance of this issue.

http://jsonapi.org/format/#document-structure-compound-documents

**Comment by wwwdata** [comment]
yeah, they changed it from linked to included like 2 days ago

**Comment by ben-crowhurst** [comment]
Ah, sorry to pester.

**Comment by wwwdata** [comment]
No, we needed this ticket anyway! thx :trollface:
