### ISSUE TITLE
JSON API RC3 tracking

### ISSUE THREAD

**Issue by steveklabnik** [univedo/api2go#78]
Hey there! I just wanted to let you know that JSON API has hit RC3, and we'd like client libraries to start implementing it like it was 1.0, as a final check that we're good for 1.0. I wanted to make this issue to let you know!

https://github.com/json-api/json-api/issues/484

**Comment by wwwdata** [comment]
awesome!

**Comment by steveklabnik** [comment]
:confetti_ball:

**Comment by sharpner** [comment]
diff rc2 -> rc3: https://gist.github.com/bobholt/1a5e9103be5fa85a53da

**Comment by wwwdata** [comment]
We have all the essential features of RC3. So far we could implement them all. I guess we can resolve this ticket?

**Comment by sharpner** [comment]
you'r right!
