### ISSUE TITLE
Interfaces for Referenced Structs

### ISSUE THREAD

**Issue by sharpner** [univedo/api2go#84]
In order to remove much of the reflection stuff, we introduce some new interfaces.

The Idea is, that we do not need any convention any more for fields with reference IDs or referenced structs. This will be handled by methods that are defined in an interface.

We need at least these 4 Methods:
```
type RefenceID struct {
  ID string
  Type string
}

```
  * GetReferencedIDs() []ReferenceID {}
  * SetReferencedIDs(IDs []ReferenceID) {}
  * GetReferencedStructs() []interface{} {}
  * SetReferencedStructs(references []interface{}) {}

**Comment by wwwdata** [comment]
Another idea: We also  introduce an interface to get the ID of a struct itself. This eliminiates a lot of the reflection bullshit magic code that we currently have and every single field in the struct that needs to be marshalled is payload without any convention!

**Comment by sharpner** [comment]
fixes #77 
fixes #84 
fixes #7
