### ISSUE TITLE
Missing Query Parameters

### ISSUE THREAD

**Issue by ben-crowhurst** [univedo/api2go#88]
Having just run `go get -u github.com/univedo/api2go`

> developer$ curl -v 'http://127.0.0.1:3001/v1/feeds/AD83C78A-4370-45D7-8FD3- 335C4C9552B3/revisions?first=4&last=5'
>
> * About to connect() to 127.0.0.1 port 3001 (#0)
> * Trying 127.0.0.1...
> * connected
> * Connected to 127.0.0.1 (127.0.0.1) port 3001 (#0)
>
> GET /v1/feeds/AD83C78A-4370-45D7-8FD3-335C4C9552B3/revisions?first=4&last=5 HTTP/1.1
> User-Agent: curl/7.24.0 (x86_64-apple-darwin12.0) libcurl/7.24.0 OpenSSL/0.9.8| zlib/1.2.5
> Host: 127.0.0.1:3001
> Accept: */*

**The only available parameters for printing are:**

2015/04/02 14:12:04 feedsID = [AD83C78A-4370-45D7-8FD3-335C4C9552B3]
2015/04/02 14:12:04 Fields: [*]

**first & last query parameters are missing :/**

```golang
    for key, values := range request.QueryParams {
        log.Println(key,"=", values)
    }
```

**Comment by wwwdata** [comment]
I quickly looked at the code and found the problem. Looks like I forgot to call the buildRequest method here https://github.com/univedo/api2go/blob/master/api.go#L223
