### ISSUE TITLE
Resources not correctly marshalled into json.

### ISSUE THREAD

**Issue by ben-crowhurst** [univedo/api2go#90]
after performing a `go get -u`

**actual**
```
{
     feedIDs: [ ... ]
}
```

**expected**
```
{
     links: {
         feeds: [ ... ]
     }
}
```

Really need to get some acceptance tests around this project.

**Comment by wwwdata** [comment]
This is the new expected behavior. We introduced the new interfaces and everything that you do not want to have in the json needs to be ignored with the json ignore tag like described in the readme. 

```
type Post struct {
  ID          int
  Title       string
  Comments    []Comment `json:"-"` // this will be ignored by the api2go marshaller
  CommentsIDs []int     `json:"-"` // it's only useful for our internal relationship handling
}
```

**Comment by ben-crowhurst** [comment]
Sorry I did read this yesterday. My mistake.

**Comment by ben-crowhurst** [comment]
So is this inline with the JSONAPI.org?

**Comment by ben-crowhurst** [comment]
Sorry I did read this yesterday. My mistake, have a good weekend.

**Comment by wwwdata** [comment]
no problem :) Have a nice weekend too. We wanted to eliminate this "magical" behavior where you needed to have special fields for IDs and Relationship structs and solved this problem by interfaces now. We think this is a much more flexible and cleaner way to do it.
